# Generated by Django 3.2 on 2022-04-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_thmbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='thmbnail',
            new_name='thumbnail',
        ),
    ]
